### ISSUE TITLE
Exception ‘View as Text'

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#64]
On a Mac, typing 

x;

in the console to create an exception and then pressing the ‘View as Text’ button causes an error:

Exception in thread "AppKit Thread" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
    at org.eclipse.swt.SWT.error(SWT.java:4441)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
    at uk.ac.mdx.xmf.swt.demo.Main.main(Main.java:573)
Caused by: java.lang.NullPointerException
    at com.ceteva.text.texteditor.TextEditor.setText(TextEditor.java:805)
    at com.ceteva.text.texteditor.TextEditorModel.processMessage(TextEditorModel.java:76)
    at uk.ac.mdx.xmf.swt.client.IdManager.processMessage(IdManager.java:88)
    at com.ceteva.text.EditorClient.processMessage(EditorClient.java:219)
    at uk.ac.mdx.xmf.swt.client.PacketDisplayRunnable.unpackPacket(PacketDisplayRunnable.java:85)
    at uk.ac.mdx.xmf.swt.client.PacketDisplayRunnable.run(PacketDisplayRunnable.java:73)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
    ... 3 more
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
    at org.eclipse.swt.SWT.error(SWT.java:4441)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4721)
    at uk.ac.mdx.xmf.swt.client.Client.sendPacket(Client.java:67)
    at xos.MessageClient.sendPacket(MessageClient.java:63)
    at engine.Machine.writePacket(Machine.java:9483)
    at foreignfuns.ForeignFuns.Kernel_writePacket(ForeignFuns.java:2793)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at foreignfuns.ForeignFun.invoke(ForeignFun.java:91)
    at engine.Machine.enterForeignFun(Machine.java:5953)
    at engine.Machine.enterOperator(Machine.java:6136)
    at engine.Machine.enter(Machine.java:5801)
    at engine.Machine.performInstrs(Machine.java:4532)
    at engine.Machine.perform(Machine.java:4307)
    at threads.ThreadInitiator.start(ThreadInitiator.java:21)
    at xos.OperatingSystem.runThread(OperatingSystem.java:1633)
    at xos.OperatingSystem.runReadyThread(OperatingSystem.java:1620)
    at xos.OperatingSystem.run(OperatingSystem.java:1600)
    at xos.OperatingSystem.init(OperatingSystem.java:652)
    at uk.ac.mdx.xmf.swt.demo.Main$5.run(Main.java:257)
Caused by: java.lang.NullPointerException
    at com.ceteva.text.texteditor.TextEditor.setText(TextEditor.java:805)
    at com.ceteva.text.texteditor.TextEditorModel.processMessage(TextEditorModel.java:76)
    at uk.ac.mdx.xmf.swt.client.IdManager.processMessage(IdManager.java:88)
    at com.ceteva.text.EditorClient.processMessage(EditorClient.java:219)
    at uk.ac.mdx.xmf.swt.client.PacketDisplayRunnable.unpackPacket(PacketDisplayRunnable.java:85)
    at uk.ac.mdx.xmf.swt.client.PacketDisplayRunnable.run(PacketDisplayRunnable.java:73)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
    at uk.ac.mdx.xmf.swt.demo.Main.main(Main.java:573)
Thread[Thread-1,5,main]: Ready(com.ceteva.forms)
Thread[Thread-1,5,main]: Thread Thread(Forms,5,ACTIVE,60,null) is blocking because com.ceteva.forms is not ready
Thread[Thread-1,5,main]: Thread Thread(Forms,5,BLOCK_READ,60,null) halted.
Thread[Thread-1,5,main]: Thread Thread(Forms,5,BLOCK_READ,60,null) is blocking on input.
Thread[Thread-1,5,main]: StartMessageMonitor(Client(com.ceteva.forms),Thread(Forms,5,BLOCK_READ,60,null))
Thread[Thread-1,5,main]: Returning from reschedule thread
MessageMonitor(Client(com.ceteva.forms),Thread(Forms,5,BLOCK_READ,60,null),ACTIVE): Message monitor MessageMonitor(Client(com.ceteva.forms),Thread(Forms,5,BLOCK_READ,60,null),ACTIVE) about to peek at Client(com.ceteva.forms)
Thread[Thread-1,5,main]: scheduledThreads = []
Thread[Thread-1,5,main]: inputMonitors = [InputMonitor(XChannel(java.io.BufferedInputStream@5f882b7d),Thread(Console,3,BLOCK_READ,262,null),ACTIVE)]
Thread[Thread-1,5,main]: messageMonitors = [MessageMonitor(Client(com.ceteva.mosaic),Thread(Mosaic,1,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.menus),Thread(Browser,2,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.undo),Thread(Undo,4,BLOCK_READ,48,null),ACTIVE), MessageMonitor(Client(com.ceteva.forms),Thread(Forms,5,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.modelBrowser),Thread(Browser,6,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.diagram),Thread(Diagrams,7,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.dialogs),Thread(Dialogs,8,BLOCK_READ,60,null),ACTIVE), MessageMonitor(Client(com.ceteva.text),Thread(Text,9,BLOCK_READ,60,null),ACTIVE)]
Thread[Thread-1,5,main]: clientThreads = []
Thread[Thread-1,5,main]: inputChannels = [XChannel(java.io.BufferedInputStream@513ee65), XChannel(java.io.BufferedInputStream@5f882b7d)]
Thread[Thread-1,5,main]: outputChannels = [java.io.PrintStream@64df4c8a, java.io.BufferedOutputStream@1a2bc3]
Thread[Thread-1,5,main]: clients = [InternalClient(com.ceteva.console,XChannel(java.io.BufferedInputStream@5f882b7d),java.io.BufferedOutputStream@1a2bc3), Client(com.ceteva.text), Client(com.ceteva.mosaic), Client(com.ceteva.menus), Client(com.ceteva.modelBrowser), Client(com.ceteva.diagram), Client(com.ceteva.dialogs), Client(com.ceteva.forms), Client(com.ceteva.undo), Client(com.ceteva.oleBridge)]
Thread[Thread-1,5,main]: threads = Thread(Forms,5,BLOCK_READ,60,null),Thread(Undo,4,BLOCK_READ,48,null),Thread(Console,3,BLOCK_READ,262,null),Thread(Browser,2,BLOCK_READ,60,null),Thread(Mosaic,1,BLOCK_READ,60,null),Thread(Text,9,BLOCK_READ,60,null),Thread(Dialogs,8,BLOCK_READ,60,null),Thread(Diagrams,7,BLOCK_READ,60,null),Thread(Browser,6,BLOCK_READ,60,null)
Thread[Thread-1,5,main]: XOS waiting for monitor notification.

**Comment by yongjun1** [comment]
run it on my laptop, it is fine, strange.
